version: '3.10'

services:
  web:
    build: .
    command: gunicorn GEN_AI_BACKEND.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
