# Generated by Django 5.0 on 2023-12-12 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("last_updated_by", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sub_category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategoryPromptCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("foundation_model", models.CharField(max_length=255)),
                ("prompt_code", models.CharField(max_length=255)),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productsubcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_code", models.CharField(max_length=255)),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productsubcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=255)),
                ("foundation_model", models.CharField(max_length=255)),
                ("rag", models.CharField(max_length=10)),
                ("prompt", models.CharField(max_length=255)),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sequence_no", models.IntegerField()),
                ("executable_prompt", models.BooleanField()),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.prompt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategoryPrompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sequence_no", models.IntegerField()),
                ("executable_prompt", models.BooleanField()),
                ("status", models.BooleanField()),
                ("valid_till", models.DateField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.customer"
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productcategory",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.prompt"
                    ),
                ),
            ],
        ),
    ]
