# Generated by Django 5.0 on 2023-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_valid_till_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prompts",
            field=models.ManyToManyField(
                blank=True, related_name="prompts", to="product.prompt"
            ),
        ),
    ]
