# Generated by Django 5.0 on 2023-12-13 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_prompts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="prompts",
        ),
    ]
