# Generated by Django 5.0 on 2023-12-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_product_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prompts",
            field=models.ManyToManyField(
                blank=True,
                related_name="prompts",
                through="product.ProductPrompt",
                to="product.prompt",
            ),
        ),
    ]
