# Generated by Django 5.0 on 2023-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="prompts",
            field=models.ManyToManyField(
                blank=True,
                related_name="product_category",
                through="product.ProductCategoryPrompt",
                to="product.prompt",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="prompts",
            field=models.ManyToManyField(
                blank=True,
                related_name="product",
                through="product.ProductPrompt",
                to="product.prompt",
            ),
        ),
    ]
