# Generated by Django 5.0 on 2023-12-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_productcategory_prompts_alter_product_prompts"),
        ("user", "0004_alter_user_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="product.productsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="productcategorypromptcode",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category_prompt_code",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="productcategorypromptcode",
            name="product_sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category_prompt_code",
                to="product.productsubcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sub_category",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="product_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sub_category",
                to="product.productcategory",
            ),
        ),
    ]
