# Generated by Django 5.0 on 2023-12-13 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_product_customer_and_more"),
        ("user", "0004_alter_user_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategoryprompt",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category_prompt",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="productcategoryprompt",
            name="product_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category_prompt",
                to="product.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="productprompt",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_prompt",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="productprompt",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_prompt",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="productprompt",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_prompt",
                to="product.prompt",
            ),
        ),
    ]
