# Generated by Django 5.0.1 on 2024-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_testcases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategoryprompt",
            name="executable_prompt",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="productprompt",
            name="executable_prompt",
            field=models.CharField(max_length=500),
        ),
    ]
