# Generated by Django 5.0.1 on 2024-01-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_productcategoryprompt_executable_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcases",
            name="data_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
