# Generated by Django 5.0.1 on 2024-01-10 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_testcases_data_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcases",
            name="test_type",
        ),
    ]
