# Generated by Django 5.0.1 on 2024-01-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_remove_testcases_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="testtype",
            name="executable_codes",
            field=models.JSONField(default={}),
        ),
    ]
