# Generated by Django 5.0.1 on 2024-01-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_testtype_executable_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcases",
            name="test_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="product.testtype",
            ),
            preserve_default=False,
        ),
    ]
