# Generated by Django 5.0.1 on 2024-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_foundationalmodel_alter_prompt_last_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testtype",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testtype",
            name="code",
            field=models.CharField(max_length=500),
        ),
    ]
