# Generated by Django 5.0.1 on 2024-01-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_testtype_name_alter_testtype_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategories",
            name="executable_codes",
            field=models.JSONField(default={}),
        ),
    ]
