# Generated by Django 5.0.1 on 2024-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_alter_product_last_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcases",
            name="sha",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
