# Generated by Django 5.0.1 on 2024-01-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_testcases_sha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcases",
            name="test_type",
        ),
        migrations.AddField(
            model_name="testcases",
            name="test_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="product.testcategories",
            ),
            preserve_default=False,
        ),
    ]
