# Generated by Django 5.0.1 on 2024-01-24 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_remove_testcases_test_type_testcases_test_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcategories",
            name="last_updated_by",
        ),
    ]
