# Generated by Django 5.0.1 on 2024-01-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_remove_testcategories_last_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategories",
            name="last_updated_by",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_category_last_updated",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
