# Generated by Django 4.2.9 on 2024-01-31 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_routerdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0022_testcategories_last_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScriptExecResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pass_count', models.IntegerField()),
                ('fail_count', models.IntegerField()),
                ('comments', models.TextField()),
                ('execution_result_details', models.JSONField(default={})),
                ('test_script_number', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_script_exec_results', to='user.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_script_exec_results', to='product.product')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_script_exec_results', to='product.testcategories')),
            ],
        ),
    ]
