# Generated by Django 4.2.9 on 2024-01-31 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_testscriptexecresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscriptexecresults',
            name='product_sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='test_script_exec_results', to='product.productsubcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testscriptexecresults',
            name='test_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='test_script_exec_results', to='product.testtype'),
            preserve_default=False,
        ),
    ]
