# Generated by Django 5.0.1 on 2024-02-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0024_testscriptexecresults_product_sub_category_and_more"),
        ("user", "0006_delete_routerdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuredTestCases",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("test_id", models.CharField(db_index=True, max_length=100)),
                ("test_name", models.CharField(max_length=255)),
                ("objective", models.CharField(max_length=500)),
                ("data", models.JSONField()),
                ("type", models.CharField(max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_test_cases",
                        to="user.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_test_cases",
                        to="product.product",
                    ),
                ),
                (
                    "test_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_test_cases",
                        to="product.testcategories",
                    ),
                ),
            ],
        ),
    ]
