# Generated by Django 5.0.1 on 2024-02-07 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0027_testcases_request"),
        ("user", "0015_alter_requesttracking_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredtestcases",
            name="request",
            field=models.ForeignKey(
                blank=True,
                db_column="request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_test_cases",
                to="user.requesttracking",
            ),
        ),
        migrations.AlterField(
            model_name="testcases",
            name="request",
            field=models.ForeignKey(
                blank=True,
                db_column="request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="user.requesttracking",
            ),
        ),
    ]
