# Generated by Django 5.0.1 on 2024-02-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0028_alter_structuredtestcases_request_and_more"),
        ("user", "0016_alter_requesttracking_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredtestcases",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_test_cases",
                to="user.requesttracking",
                to_field="request_id",
            ),
        ),
        migrations.AlterField(
            model_name="testcases",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="user.requesttracking",
                to_field="request_id",
            ),
        ),
    ]
