# Generated by Django 5.0.1 on 2024-02-07 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0029_alter_structuredtestcases_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuredtestcases",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="structuredtestcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 6, 10, 13, 25, 438708, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testcases",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="testcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 6, 10, 13, 37, 70424, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
