# Generated by Django 5.0.1 on 2024-02-07 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0031_structuredtestcases_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredtestcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 6, 14, 0, 32, 12913, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="testcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 6, 14, 0, 32, 10913, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
