# Generated by Django 5.0.1 on 2024-02-12 07:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0032_alter_structuredtestcases_valid_till_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structuredtestcases",
            name="test_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_test_cases",
                to="product.testtype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="structuredtestcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 11, 6, 59, 49, 524131, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="testcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 11, 6, 59, 49, 523131, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
