# Generated by Django 5.0.1 on 2024-02-13 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0033_structuredtestcases_test_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredtestcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 12, 7, 58, 39, 687884, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="testcases",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 12, 7, 58, 39, 686882, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
