# Generated by Django 4.2.9 on 2024-03-17 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_product_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundationalmodel',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategoryprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategorypromptcode',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='structuredtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testscriptexecresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 8, 12, 22, 367939, tzinfo=datetime.timezone.utc)),
        ),
    ]
