# Generated by Django 5.0.2 on 2024-03-19 05:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_knowledgebaseprompts_default_data_and_more'),
        ('user', '0039_alter_accesstype_valid_till_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseprompts',
            name='updated_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_prompts_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vector_name_space',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundationalmodel',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseprompts',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_prompts_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgebaseprompts',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategoryprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategorypromptcode',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='structuredtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testscriptexecresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='KnowledgeBaseResults',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('valid_till', models.DateField(default=datetime.datetime(2025, 3, 19, 5, 7, 44, 964, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('top_k_docs', models.JSONField()),
                ('summary_of_docs', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_results_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_results', to='user.customer')),
                ('kb_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_results', to='product.knowledgebaseprompts')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_results', to='user.requesttracking')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_results_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
