# Generated by Django 5.0.2 on 2024-03-19 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_knowledgebaseprompts_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebaseresults',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='foundationalmodel',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseprompts',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategoryprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategorypromptcode',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='structuredtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testscriptexecresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 5, 26, 11, 441294, tzinfo=datetime.timezone.utc)),
        ),
    ]
