# Generated by Django 4.2.9 on 2024-03-25 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0087_alter_foundationalmodel_valid_till_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_product_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_product_sub_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foundationalmodel',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseprompts',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategoryprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategorypromptcode',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='structuredtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testscriptexecresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 25, 9, 44, 43, 961860, tzinfo=datetime.timezone.utc)),
        ),
    ]
