# Generated by Django 5.0.2 on 2024-04-16 08:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0093_alter_documentuploads_valid_till_and_more'),
        ('user', '0049_alter_accesstype_valid_till_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuploads',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='foundationalmodel',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseprompts',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategoryprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategorypromptcode',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='structuredtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testscriptexecresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserCreatedTestCases',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('valid_till', models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_id', models.CharField(db_index=True, max_length=100)),
                ('test_name', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=500)),
                ('data', models.JSONField()),
                ('type', models.CharField(max_length=20)),
                ('comment', models.CharField(default='USER CREATED', max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_test_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_test_cases', to='user.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_test_cases', to='product.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_test_cases', to='user.requesttracking', to_field='request_id')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_test_cases', to='product.testcategories')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_test_cases', to='product.testtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]