# Generated by Django 4.2.9 on 2024-04-25 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_alter_documentuploads_valid_till_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuploads',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='foundationalmodel',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseprompts',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='knowledgebaseresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategoryprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productcategorypromptcode',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productprompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='structuredtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testscriptexecresults',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testsubcategories',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usercreatedtestcases',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 25, 3, 55, 57, 154863, tzinfo=datetime.timezone.utc)),
        ),
    ]
