# Generated by Django 5.0.2 on 2024-03-26 09:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0046_alter_accesstype_valid_till_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronExecution',
            fields=[
                ('status', models.BooleanField(default=True)),
                ('valid_till', models.DateField(default=datetime.datetime(2025, 3, 26, 9, 2, 21, 827356, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pickup_time', models.DateTimeField()),
                ('is_executable', models.BooleanField(default=True)),
                ('execution_status', models.CharField(choices=[('PENDING', 'PENDING'), ('EXECUTING', 'EXECUTING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=15)),
                ('params', models.JSONField()),
                ('results', models.JSONField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_execution', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_execution', to='user.customer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_execution', to='user.requesttracking', to_field='request_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
