# Generated by Django 5.0.2 on 2024-03-26 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_alter_cronexecution_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='results',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 9, 30, 35, 275183, tzinfo=datetime.timezone.utc)),
        ),
    ]
