# Generated by Django 5.0.2 on 2024-03-26 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_alter_cronexecution_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 9, 48, 29, 606961)),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 9, 48, 29, 592849, tzinfo=datetime.timezone.utc)),
        ),
    ]
