# Generated by Django 5.0.2 on 2024-03-26 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_alter_cronexecution_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='execution_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXECUTING', 'EXECUTING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 9, 54, 3, 791511)),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 9, 54, 3, 771020, tzinfo=datetime.timezone.utc)),
        ),
    ]
