# Generated by Django 5.0.2 on 2024-03-26 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_alter_cronexecution_execution_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 9, 57, 15, 782954)),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 3, 26, 9, 57, 15, 767898, tzinfo=datetime.timezone.utc)),
        ),
    ]
