# Generated by Django 5.0.2 on 2024-04-16 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_alter_cronexecution_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 16, 8, 41, 36, 493338)),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 16, 8, 41, 36, 467357, tzinfo=datetime.timezone.utc)),
        ),
    ]
