# Generated by Django 5.0.6 on 2024-05-29 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0007_alter_cronexecution_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 10, 40, 5, 386871)),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 5, 29, 5, 10, 5, 306728, tzinfo=datetime.timezone.utc)),
        ),
    ]
