# Generated by Django 5.0.1 on 2024-05-23 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0007_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 23, 16, 54, 59, 498744)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
