# Generated by Django 5.0.6 on 2024-05-29 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0008_alter_cronexecution_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronexecution',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 14, 20, 15, 567859)),
        ),
        migrations.AlterField(
            model_name='cronexecution',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 5, 29, 8, 50, 15, 448310, tzinfo=datetime.timezone.utc)),
        ),
    ]
