# Generated by Django 5.0.1 on 2024-06-05 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0010_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 5, 14, 50, 55, 9917)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
