# Generated by Django 5.0.1 on 2024-06-26 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0013_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 26, 10, 10, 6, 900081)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 26, 4, 40, 6, 859985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
