# Generated by Django 5.0.1 on 2024-07-01 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0015_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 1, 10, 12, 31, 203112)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 1, 4, 42, 31, 144721, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
