# Generated by Django 5.0.1 on 2024-07-02 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0016_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 2, 23, 25, 47, 170415)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 2, 17, 55, 47, 129808, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
