# Generated by Django 5.0.1 on 2024-07-15 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0018_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 15, 10, 23, 45, 154029)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 53, 45, 120496, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
