# Generated by Django 5.0.1 on 2024-07-24 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_manager", "0020_alter_cronexecution_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronexecution",
            name="pickup_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 24, 10, 55, 54, 587381)
            ),
        ),
        migrations.AlterField(
            model_name="cronexecution",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 24, 5, 25, 54, 546859, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
