# Generated by Django 5.0 on 2023-12-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="valid_till",
            field=models.DateField(blank=True),
        ),
    ]
