# Generated by Django 5.0 on 2023-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_customer_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstype",
            name="valid_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="valid_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="valid_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="valid_till",
            field=models.DateField(blank=True, null=True),
        ),
    ]
