# Generated by Django 5.0 on 2023-12-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_accesstype_valid_till_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.customer",
            ),
        ),
    ]
