# Generated by Django 5.0 on 2023-12-13 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerconfig",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_config",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="user.customer",
            ),
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_access",
                to="user.customer",
            ),
        ),
    ]
