# Generated by Django 4.2.9 on 2024-02-02 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_routerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('api', models.CharField(max_length=255)),
                ('payload', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
