# Generated by Django 4.2.9 on 2024-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_created_at_requesttracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracking',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
