# Generated by Django 4.2.9 on 2024-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_requesttracking_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttracking',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
