# Generated by Django 4.2.9 on 2024-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_requesttracking_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracking',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
