# Generated by Django 5.0.1 on 2024-02-07 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_requesttracking_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesttracking",
            name="created_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_tracking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
