# Generated by Django 5.0.1 on 2024-02-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0015_alter_requesttracking_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesttracking",
            name="request_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
