# Generated by Django 5.0.1 on 2024-02-13 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_alter_requesttracking_request_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
