# Generated by Django 5.0.1 on 2024-02-15 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_alter_user_options_requesttracking_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_name",
            field=models.CharField(default="user", max_length=255),
        ),
        migrations.AlterField(
            model_name="accesstype",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 14, 8, 48, 7, 195855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 14, 8, 48, 7, 195855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 14, 8, 48, 7, 195855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="requesttracking",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 14, 8, 48, 7, 195855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 14, 8, 48, 7, 195855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 14, 8, 48, 7, 195855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
