# Generated by Django 4.2.9 on 2024-04-17 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_alter_accesstype_valid_till_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='accesstype',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 8, 16, 25, 208076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 8, 16, 25, 208076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customerconfig',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 8, 16, 25, 208076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='requesttracking',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 8, 16, 25, 208076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 8, 16, 25, 208076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='valid_till',
            field=models.DateField(default=datetime.datetime(2025, 4, 17, 8, 16, 25, 208076, tzinfo=datetime.timezone.utc)),
        ),
    ]
