# Generated by Django 5.0.1 on 2024-05-23 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0052_alter_accesstype_valid_till_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requesttracking",
            name="meta_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="accesstype",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="requesttracking",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 5, 23, 11, 24, 59, 462362, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
