# Generated by Django 5.0.1 on 2024-06-05 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0055_alter_accesstype_valid_till_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstype",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="requesttracking",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 6, 5, 9, 20, 54, 971749, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
