# Generated by Django 5.0.1 on 2024-07-15 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0064_alter_accesstype_valid_till_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstype",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 57, 56, 667515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 57, 56, 667515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="customerconfig",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 57, 56, 667515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="requesttracking",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 57, 56, 667515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 57, 56, 667515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="useraccess",
            name="valid_till",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 7, 15, 4, 57, 56, 667515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
